### ISSUE TITLE
Stops working after a few restarts

### ISSUE THREAD

**Issue by Sporif** [AlexEndris/tst-middleclick#1]
After a few restarts the extension simply work and middle click goes back to opening a new tab. In the console this is what I get:
```
Registering with TST
Unknown localization message extensionname 
```
The second line is always there and on first install it manages to register successfully. After the 1st and 2nd restarts it still works. But strangely on the 3rd+ restarts it stops working. Disabling and re-enabling it fixes it, but only for one or two restarts.

According to [this](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n) you need to first include the localized string in locale files packaged with your extension, but there are no locale files in yours. So it's being registered with an empty string.

In any case think this is a better way to register the addon:
```
    console.log("Registering with TST");
    var self = await browser.management.getSelf();
    var success = await browser.runtime.sendMessage(treeStyleTabId, {
        type: 'register-self',
        name: self.id
    });
```

A good thing is that `browser.management.getSelf` doesn't require the 'management' permission. See [here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/management/getSelf).

But I'm not sure this will fix it as another TST extension had the same [problem](https://github.com/joshuacant/tst-wheel_and_double/issues/1) and fixed it a different way. See this [commit](https://github.com/joshuacant/tst-wheel_and_double/commit/af9533e71343bd0745119d3c6cf02bc1ecebd60d).

**Comment by AlexEndris** [comment]
Thank you for the detailed report. I've experienced it myself, but as long as it was only me, I didn't bother looking for a solution. I'll give your solution a try before using a timer.

**Comment by AlexEndris** [comment]
@Sporif I've just uploaded the new version. Trying locally, registering worked fine.

It should be up soon:
https://addons.mozilla.org/en-GB/firefox/addon/tst-middleclick/

Thanks again for your suggestion!

**Comment by Sporif** [comment]
Yep, can confirm it's fixed. Thank you for updating.
