### ISSUE TITLE
Option for closing active tab instead of restoring [FEATURE REQUEST]

### ISSUE THREAD

**Issue by emvaized** [AlexEndris/tst-middleclick#5]
Hi!
I've created a simple fork of your extension, with only change that it allows user to close current tab instead of restoring.

I've changed just a few lines in `middleClick.js` file, but I'm not sure what to change else to publish it to Firefox store, and whether it's really worth it considering such a small change I made to your code. 

Can you please do it, and publish it as an another extension from your developer account? 
Here's the link to the ZIP-file with my changes:

[https://drive.google.com/open?id=1RZPxW3zk5C3crBmla2gGsveGw3sx267e](https://drive.google.com/open?id=1RZPxW3zk5C3crBmla2gGsveGw3sx267e)

P.S.: Maybe you may also consider to add this feature as an option in your existing extension's settings.

**Comment by AlexEndris** [comment]
Hi,

I'd much rather incorporate this as an option than pushing another package that does something similar. I think that would be confusing.

How about you just make a pull request with your changes (and of course the configurable option)? I'd very much appreciate that.

Cheers Alex

**Comment by emvaized** [comment]
> Hi,
> 
> I'd much rather incorporate this as an option than pushing another package that does something similar. I think that would be confusing.
> 
> How about you just make a pull request with your changes (and of course the configurable option)? I'd very much appreciate that.
> 
> Cheers Alex

Thanks, Alex.

I will study how to create configurable options in firefox add-ons in my free time, and then'll make a pull request.

**Comment by AlexEndris** [comment]
Sweet. You could use this to jump start: 

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Options_pages

https://github.com/mdn/webextensions-examples/tree/master/favourite-colour

**Comment by emvaized** [comment]
> Sweet. You could use this to jump start:
> 
> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Options_pages
> 
> https://github.com/mdn/webextensions-examples/tree/master/favourite-colour

I'm sorry, I tried and didn't managed to succeed due to the lack experience in JS. Seems for now I'll have to stick with reinstalling my version as temporal add-on on every restart of Firefox.

**Comment by AlexEndris** [comment]
@emvaized Take a look at my pull request. A quick test on my side worked well. Can you perhaps take that version and give it a test run if that fits your needs?

**Comment by emvaized** [comment]
@AlexEndris Yeah, it works just fine! Thanks a lot!
I implemented options just as you did, but got stuck with middleClick handler file...

Can you please update your add-on in firefox store with this new feature?

**Comment by AlexEndris** [comment]
@emvaized Pinging you, as I just pushed it to mozilla's extensions. Should be there shortly.
