### ISSUE TITLE
'Middle click to close current tab' closes active tab in all open windows

### ISSUE THREAD

**Issue by emvaized** [AlexEndris/tst-middleclick#7]
I guess this code from `middleClick.js `:
```
let activeTabs = await browser.tabs.query({ active: true });
for (let tab of activeTabs) {
   browser.tabs.remove(tab.id);
}
```
should have a check for parse only tabs from current window of middle click.

**Comment by emvaized** [comment]
Just attempted to fix it in pull request https://github.com/AlexEndris/tst-middleclick/pull/8

**Comment by AlexEndris** [comment]
Considering you fixed it (just tested it) I close this here. Thank you for your contribution!

**Comment by AlexEndris** [comment]
@emvaized Enjoy and thank you again for your help! 

https://addons.mozilla.org/en-US/firefox/addon/tst-middleclick/

**Comment by emvaized** [comment]
@AlexEndris 
Great! Many thanks for such quick response 👍
